name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "$SUPER_SECRET"

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zakkg3/debugtool:$(date +%s) --tag zakkg3/debugtool:latest

    - name: Push
      run: docker push zakkg3/debugtool:$(date +%s)
      run: docker push zakkg3/debugtool:latest